"""hands' models must match lib/contracts (generated by scripts/gen_schemas.py)."""
from __future__ import annotations

import json
import sys
from pathlib import Path

import jsonschema

from hands.models import Feedback, ProjectConfig

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "hands" / "scripts"))
import gen_schemas  # noqa: E402


def test_committed_schemas_are_current() -> None:
    for name, model in gen_schemas.MODELS.items():
        committed = json.loads((ROOT / "lib" / "contracts" / f"{name}.schema.json").read_text())
        assert committed == gen_schemas.build(name, model), \
            f"stale {name} contract: run `uv run python scripts/gen_schemas.py` in hands/"


def test_instances_validate() -> None:
    pc = json.loads(ProjectConfig(name="t").model_dump_json())
    jsonschema.validate(pc, gen_schemas.build("project-config", ProjectConfig))
    fb = Feedback(session_id="s", render_path="r.wav", text="ok", timestamp_utc="2026-09-30T00:00:00Z", rating=4)
    jsonschema.validate(json.loads(fb.model_dump_json()), gen_schemas.build("feedback", Feedback))
