local backup = require("core.backup")

describe("backup.projectNameFromPath", function()
  it("extracts name from full path", function()
    assert.equals("MyTrack", backup.projectNameFromPath("/Music/Ableton/Projects/MyTrack/MyTrack.als"))
  end)
  it("falls back to 'project' when no .als extension", function()
    assert.equals("project", backup.projectNameFromPath("/music/noext"))
  end)
end)

describe("backup.projectBackupDir", function()
  it("builds dir path with trailing slash", function()
    assert.equals("/iCloud/Backups/MyTrack/", backup.projectBackupDir("/iCloud/Backups", "MyTrack"))
  end)
end)

describe("backup.backupPath", function()
  it("builds full backup path", function()
    local result = backup.backupPath("/iCloud/Backups", "MyTrack", "20260804_090000")
    assert.equals("/iCloud/Backups/MyTrack/MyTrack_20260804_090000.als", result)
  end)
end)

describe("backup.filesToDelete", function()
  it("returns empty when list is empty", function()
    assert.same({}, backup.filesToDelete({}, 3))
  end)
  it("returns empty when fewer than max", function()
    assert.same({}, backup.filesToDelete({"a.als", "b.als"}, 5))
  end)
  it("returns empty when exactly max", function()
    assert.same({}, backup.filesToDelete({"a.als", "b.als", "c.als"}, 3))
  end)
  it("deletes oldest when more than max", function()
    local files = {"a.als", "b.als", "c.als", "d.als", "e.als"}
    assert.same({"a.als", "b.als"}, backup.filesToDelete(files, 3))
  end)
  it("deletes all when maxKeep is 0", function()
    assert.same({"a.als", "b.als"}, backup.filesToDelete({"a.als", "b.als"}, 0))
  end)
end)
