local filename = require("core.filename")

describe("filename.sanitize", function()
  it("strips spaces", function()
    assert.equals("hello_world", filename.sanitize("hello world"))
  end)
  it("collapses repeated underscores", function()
    assert.equals("a_b", filename.sanitize("a__b"))
  end)
  it("trims leading and trailing underscores", function()
    assert.equals("hello", filename.sanitize("_hello_"))
  end)
  it("preserves hyphens", function()
    assert.equals("my-task", filename.sanitize("my-task"))
  end)
  it("handles empty string", function()
    assert.equals("", filename.sanitize(""))
  end)
  it("strips special chars", function()
    assert.equals("a_b_c", filename.sanitize("a/b:c"))
  end)
end)

describe("filename.timestampedName", function()
  it("returns stamp alone when part is empty", function()
    assert.equals("20260802_143000", filename.timestampedName("20260802_143000", ""))
  end)
  it("appends part with underscore separator", function()
    assert.equals("20260802_143000_my_task", filename.timestampedName("20260802_143000", "my_task"))
  end)
end)

describe("filename.copyPath", function()
  it("builds copy path with timestamp", function()
    local result = filename.copyPath("/music/project.als", "20260802_143000")
    assert.equals("/music/project_copy_20260802_143000.als", result)
  end)
  it("uses 'project' as fallback name when no .als extension", function()
    local result = filename.copyPath("/music/noext", "20260802_143000")
    assert.equals("/music/project_copy_20260802_143000.als", result)
  end)
  it("uses '.' as fallback dir when no directory", function()
    local result = filename.copyPath("project.als", "20260802_143000")
    assert.equals("./project_copy_20260802_143000.als", result)
  end)
end)

describe("filename.parseTaskPrompt", function()
  it("parses a SAVE: response", function()
    local name, skipped = filename.parseTaskPrompt("SAVE:my task")
    assert.equals("my task", name)
    assert.is_false(skipped)
  end)
  it("treats SKIP as skipped", function()
    local _, skipped = filename.parseTaskPrompt("SKIP")
    assert.is_true(skipped)
  end)
  it("treats nil as skipped", function()
    local _, skipped = filename.parseTaskPrompt(nil)
    assert.is_true(skipped)
  end)
  it("treats unknown prefix as skipped", function()
    local name, skipped = filename.parseTaskPrompt("garbage")
    assert.equals("", name)
    assert.is_true(skipped)
  end)
  it("parses empty SAVE: as empty string (not skipped)", function()
    local name, skipped = filename.parseTaskPrompt("SAVE:")
    assert.equals("", name)
    assert.is_false(skipped)
  end)
end)
