local geometry = require("core.geometry")

describe("geometry.pointInRect", function()
  local r = { x=10, y=20, w=100, h=50 }

  it("returns true for a point inside", function()
    assert.is_true(geometry.pointInRect(50, 40, r))
  end)
  it("returns true at the top-left corner (inclusive)", function()
    assert.is_true(geometry.pointInRect(10, 20, r))
  end)
  it("returns false at the right edge (exclusive)", function()
    assert.is_false(geometry.pointInRect(110, 40, r))
  end)
  it("returns false at the bottom edge (exclusive)", function()
    assert.is_false(geometry.pointInRect(50, 70, r))
  end)
  it("returns false for a point above", function()
    assert.is_false(geometry.pointInRect(50, 19, r))
  end)
  it("returns false for a point to the left", function()
    assert.is_false(geometry.pointInRect(9, 40, r))
  end)
  it("returns false for a point far outside", function()
    assert.is_false(geometry.pointInRect(500, 500, r))
  end)
end)
