local log = require("core.log")

describe("core.log.record", function()
  it("returns a table with required fields", function()
    local r = log.record("info", "hello", nil, 1234567890)
    assert.equals("info", r.level)
    assert.equals("hello", r.msg)
    assert.equals(1234567890, r.ts)
  end)
  it("includes fields when provided", function()
    local r = log.record("warn", "something", { key = "val" }, 100)
    assert.equals("val", r.fields.key)
  end)
  it("sets module from fields.module", function()
    local r = log.record("debug", "msg", { module = "mymod" }, 0)
    assert.equals("mymod", r.module)
  end)
  it("module is nil when fields is nil", function()
    local r = log.record("error", "msg", nil, 0)
    assert.is_nil(r.module)
  end)
  it("fields is nil when not provided", function()
    local r = log.record("info", "msg", nil, 0)
    assert.is_nil(r.fields)
  end)
end)
